spring:
  application:
    name: log-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: main
  datasource:
    generate-unique-name: false

server:
  port: 8083